/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package group.pkg3.bse203150.bse203088.a3;

/**
 *
 * @author sahaf
 */
public class DoctorInfo extends javax.swing.JFrame {

    /**
     * Creates new form DoctorInfo
     */
    public DoctorInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        doc_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        doc_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        doc_fn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        doc_email = new javax.swing.JTextField();
        doc_contact = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        doc_qual = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        doc_bldgrp = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        doc_gender = new javax.swing.JComboBox<>();
        add_doc = new javax.swing.JButton();
        update_doc = new javax.swing.JButton();
        del_doc = new javax.swing.JButton();
        get_data = new javax.swing.JButton();
        new_doc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        jPanel1.add(doc_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 90, -1));

        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        doc_name.setText(".");
        jPanel1.add(doc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 90, -1));

        jLabel3.setText("Father Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        doc_fn.setText(".");
        jPanel1.add(doc_fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 90, -1));

        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        doc_email.setText(".");
        jPanel1.add(doc_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 130, -1));

        doc_contact.setText(".");
        jPanel1.add(doc_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 110, -1));

        jLabel5.setText("Contact");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel6.setText("Qualification");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        doc_qual.setText(".");
        jPanel1.add(doc_qual, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 110, -1));

        jLabel7.setText("Blood Group");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        doc_bldgrp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jPanel1.add(doc_bldgrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jLabel8.setText("Gender");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        doc_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jPanel1.add(doc_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, -1));

        add_doc.setText("Add Doctor");
        add_doc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_docActionPerformed(evt);
            }
        });
        jPanel1.add(add_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        update_doc.setText("Update");
        jPanel1.add(update_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        del_doc.setText("Delete");
        jPanel1.add(del_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        get_data.setText("Get Data");
        jPanel1.add(get_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        new_doc.setText("New");
        jPanel1.add(new_doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_docActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_docActionPerformed
        // TODO add your handling code here:
        
       int id = Integer.parseInt(doc_id.getText());
        String name = doc_name.getText();
        String fatherName = doc_fn.getText();
        String email = doc_email.getText();
        int contact = Integer.parseInt(doc_contact.getText());
        
        String qual = doc_qual.getText();
        String gender = (String) doc_gender.getSelectedItem();
        String bloodGroup = (String) doc_bldgrp.getSelectedItem();
        
        DoctorDAO add_doc=new DoctorDAO();
        Doctor doc=new Doctor(id,name,fatherName,email,contact,address,qual,gender,bloodGroup,joiningDate);
        add_doc.create(doc);
        
        
    }//GEN-LAST:event_add_docActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_doc;
    private javax.swing.JButton del_doc;
    private javax.swing.JComboBox<String> doc_bldgrp;
    private javax.swing.JTextField doc_contact;
    private javax.swing.JTextField doc_email;
    private javax.swing.JTextField doc_fn;
    private javax.swing.JComboBox<String> doc_gender;
    private javax.swing.JTextField doc_id;
    private javax.swing.JTextField doc_name;
    private javax.swing.JTextField doc_qual;
    private javax.swing.JButton get_data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton new_doc;
    private javax.swing.JButton update_doc;
    // End of variables declaration//GEN-END:variables
}
